### ISSUE TITLE
Prevent common security issues

### ISSUE THREAD

**Issue by aewens** [tildecross/tildex-txdb#1]
Currently, TxDB uses MongoDB through PyMongo (flask_pymongo, to be exact). The main action of interactions with MongoDB is in the file `app/views.py` (the database logic will later be abstracted out of views, but that's where it is right now). What is needed is checks put in place to prevent basic NoSQL injections or malicious behavior against the database.

Right now user input is take from **/api/v1/services** and **/api/v1/storage** through POST requests via **name** and **data** in the functions **handle_services** and **post_storage**. 

Since security is a broad spectrum, this issue will be kept open indefinitely, regardless of how many pull requests are sent.

And to anyone sending pull requests for Hacktoberfest, happy hacking!

**Comment by peter-parque** [comment]
Could I take a crack at this?

**Comment by aewens** [comment]
@peter-parque Absolutely!
